package Modelo;
// Generated 31/03/2014 16:06:45 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Auditoriaspresupuestos generated by hbm2java
 */
public class Auditoriaspresupuestos  implements java.io.Serializable {


     private Integer idauditoriapres;
     private Presupuestos presupuestos;
     private boolean esnueva;
     private Date fecha;

    public Auditoriaspresupuestos() {
    }

    public Auditoriaspresupuestos(Presupuestos presupuestos, boolean esnueva, Date fecha) {
       this.presupuestos = presupuestos;
       this.esnueva = esnueva;
       this.fecha = fecha;
    }
   
    public Integer getIdauditoriapres() {
        return this.idauditoriapres;
    }
    
    public void setIdauditoriapres(Integer idauditoriapres) {
        this.idauditoriapres = idauditoriapres;
    }
    public Presupuestos getPresupuestos() {
        return this.presupuestos;
    }
    
    public void setPresupuestos(Presupuestos presupuestos) {
        this.presupuestos = presupuestos;
    }
    public boolean isEsnueva() {
        return this.esnueva;
    }
    
    public void setEsnueva(boolean esnueva) {
        this.esnueva = esnueva;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }




}


