package Modelo;
// Generated 05/02/2014 14:26:02 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Auditoriaordenrep generated by hbm2java
 */
public class Auditoriaordenrep  implements java.io.Serializable {


     private Integer idauditoriaordrep;
     private Ordenreparacion ordenreparacion;
     private boolean esnueva;
     private Date fecha;

    public Auditoriaordenrep() {
    }

    public Auditoriaordenrep(Ordenreparacion ordenreparacion, boolean esnueva, Date fecha) {
       this.ordenreparacion = ordenreparacion;
       this.esnueva = esnueva;
       this.fecha = fecha;
    }
   
    public Integer getIdauditoriaordrep() {
        return this.idauditoriaordrep;
    }
    
    public void setIdauditoriaordrep(Integer idauditoriaordrep) {
        this.idauditoriaordrep = idauditoriaordrep;
    }
    public Ordenreparacion getOrdenreparacion() {
        return this.ordenreparacion;
    }
    
    public void setOrdenreparacion(Ordenreparacion ordenreparacion) {
        this.ordenreparacion = ordenreparacion;
    }
    public boolean isEsnueva() {
        return this.esnueva;
    }
    
    public void setEsnueva(boolean esnueva) {
        this.esnueva = esnueva;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }




}


