package Modelo;
// Generated 05/02/2014 14:26:02 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente extends Persona implements java.io.Serializable {


     private Integer idcliente;
     private Set<Ordenrecepcion> ordenrecepcions = new HashSet<Ordenrecepcion>(0);
     private Set<Ordenreparacion> ordenreparacions = new HashSet<Ordenreparacion>(0);

    public Cliente() 
    {
        super();
    }
    
    public Cliente(int dni, String nombre, String apellido, Date fechaNac, String telFijo, String telMovil, String email, String calle, String numeracion, String depto)
    {
        super(dni,nombre,apellido,fechaNac,telFijo,telMovil,email,calle,numeracion,depto);
    }

    public Cliente(Set<Ordenrecepcion> ordenrecepcions, Set<Ordenreparacion> ordenreparacions)
    {
        super();
       this.ordenrecepcions = ordenrecepcions;
       this.ordenreparacions = ordenreparacions;
    }
   
    public Integer getIdcliente() {
        return this.idcliente;
    }
    
    public void setIdcliente(Integer idcliente) {
        this.idcliente = idcliente;
    }
    
    public Set<Ordenrecepcion> getOrdenrecepcions() {
        return this.ordenrecepcions;
    }
    
    public void setOrdenrecepcions(Set<Ordenrecepcion> ordenrecepcions) {
        this.ordenrecepcions = ordenrecepcions;
    }
    public Set<Ordenreparacion> getOrdenreparacions() {
        return this.ordenreparacions;
    }
    
    public void setOrdenreparacions(Set<Ordenreparacion> ordenreparacions) {
        this.ordenreparacions = ordenreparacions;
    }




}


