package Modelo;
// Generated 31/03/2014 16:06:45 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Estadosreparacion generated by hbm2java
 */
public class Estadosreparacion  implements java.io.Serializable {


     private Integer idestado;
     private String estado;
     private Set<Ordenesreparacion> ordenesreparacions = new HashSet<Ordenesreparacion>(0);

    public Estadosreparacion() {
    }

	
    public Estadosreparacion(String estado) {
        this.estado = estado;
    }
    public Estadosreparacion(String estado, Set<Ordenesreparacion> ordenesreparacions) {
       this.estado = estado;
       this.ordenesreparacions = ordenesreparacions;
    }
   
    public Integer getIdestado() {
        return this.idestado;
    }
    
    public void setIdestado(Integer idestado) {
        this.idestado = idestado;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Set<Ordenesreparacion> getOrdenesreparacions() {
        return this.ordenesreparacions;
    }
    
    public void setOrdenesreparacions(Set<Ordenesreparacion> ordenesreparacions) {
        this.ordenesreparacions = ordenesreparacions;
    }




}


