package Modelo;
// Generated 05/02/2014 14:26:02 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Estadoreparacion generated by hbm2java
 */
public class Estadoreparacion  implements java.io.Serializable {


     private Integer idestado;
     private String estado;
     private Set<Ordenreparacion> ordenreparacions = new HashSet<Ordenreparacion>(0);

    public Estadoreparacion() {
    }

	
    public Estadoreparacion(String estado) {
        this.estado = estado;
    }
    public Estadoreparacion(String estado, Set<Ordenreparacion> ordenreparacions) {
       this.estado = estado;
       this.ordenreparacions = ordenreparacions;
    }
   
    public Integer getIdestado() {
        return this.idestado;
    }
    
    public void setIdestado(Integer idestado) {
        this.idestado = idestado;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Set<Ordenreparacion> getOrdenreparacions() {
        return this.ordenreparacions;
    }
    
    public void setOrdenreparacions(Set<Ordenreparacion> ordenreparacions) {
        this.ordenreparacions = ordenreparacions;
    }




}


