package Modelo;
// Generated 05/02/2014 14:26:02 by Hibernate Tools 3.2.1.GA



/**
 * Listarepuestos generated by hbm2java
 */
public class Listarepuestos  implements java.io.Serializable {


     private Integer idlista;
     private Tarea tarea;
     private Provrepuesto provrepuesto;

    public Listarepuestos() {
    }

    public Listarepuestos(Tarea tarea, Provrepuesto provrepuesto) {
       this.tarea = tarea;
       this.provrepuesto = provrepuesto;
    }
   
    public Integer getIdlista() {
        return this.idlista;
    }
    
    public void setIdlista(Integer idlista) {
        this.idlista = idlista;
    }
    public Tarea getTarea() {
        return this.tarea;
    }
    
    public void setTarea(Tarea tarea) {
        this.tarea = tarea;
    }
    public Provrepuesto getProvrepuesto() {
        return this.provrepuesto;
    }
    
    public void setProvrepuesto(Provrepuesto provrepuesto) {
        this.provrepuesto = provrepuesto;
    }




}


