package Modelo;
// Generated 31/03/2014 16:06:45 by Hibernate Tools 3.2.1.GA



/**
 * Listasrepuestos generated by hbm2java
 */
public class Listasrepuestos  implements java.io.Serializable {


     private Integer idlistarepuesto;
     private Tareas tareas;
     private Repuestos repuestos;
     private int cantidad;

    public Listasrepuestos() {
    }

    public Listasrepuestos(Tareas tareas, Repuestos repuestos, int cantidad) {
       this.tareas = tareas;
       this.repuestos = repuestos;
       this.cantidad = cantidad;
    }
   
    public Integer getIdlistarepuesto() {
        return this.idlistarepuesto;
    }
    
    public void setIdlistarepuesto(Integer idlistarepuesto) {
        this.idlistarepuesto = idlistarepuesto;
    }
    public Tareas getTareas() {
        return this.tareas;
    }
    
    public void setTareas(Tareas tareas) {
        this.tareas = tareas;
    }
    public Repuestos getRepuestos() {
        return this.repuestos;
    }
    
    public void setRepuestos(Repuestos repuestos) {
        this.repuestos = repuestos;
    }
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }




}


