package Modelo;
// Generated 05/02/2014 14:26:02 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Operario generated by hbm2java
 */
public class Operario extends Persona implements java.io.Serializable {


     private Integer idoperario;
     private int tipo;
     private Set<Tarea> tareas = new HashSet<Tarea>(0);

    public Operario() 
    {
        super();
    }

	
    public Operario(int tipo,int dni, String nombre, String apellido, Date fechaNac, String telFijo, String telMovil, String email, String calle, String numeracion, String depto) 
    {
        super(dni,nombre,apellido,fechaNac,telFijo,telMovil,email,calle,numeracion,depto);
        this.tipo = tipo;
    }
    public Operario( int tipo, Set<Tarea> tareas)
    {
        super();
        this.tipo = tipo;
        this.tareas = tareas;
    }
   
    public Integer getIdoperario() {
        return this.idoperario;
    }
    
    public void setIdoperario(Integer idoperario) {
        this.idoperario = idoperario;
    }
    
    public int getTipo() {
        return this.tipo;
    }
    
    public void setTipo(int tipo) {
        this.tipo = tipo;
    }
    public Set<Tarea> getTareas() {
        return this.tareas;
    }
    
    public void setTareas(Set<Tarea> tareas) {
        this.tareas = tareas;
    }




}


