package Modelo;
// Generated 31/03/2014 16:06:45 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Operarios generated by hbm2java
 */
public class Operarios  implements java.io.Serializable {


     private Integer idoperario;
     private Tiposoperario tiposoperario;
     private String nombre;
     private String usuario;
     private String pass;
     private String email;
     private Set<Tareas> tareases = new HashSet<Tareas>(0);

    public Operarios() {
    }

	
    public Operarios(Tiposoperario tiposoperario, String nombre, String usuario, String pass, String email) {
        this.tiposoperario = tiposoperario;
        this.nombre = nombre;
        this.usuario = usuario;
        this.pass = pass;
        this.email = email;
    }
    public Operarios(Tiposoperario tiposoperario, String nombre, String usuario, String pass, String email, Set<Tareas> tareases) {
       this.tiposoperario = tiposoperario;
       this.nombre = nombre;
       this.usuario = usuario;
       this.pass = pass;
       this.email = email;
       this.tareases = tareases;
    }
   
    public Integer getIdoperario() {
        return this.idoperario;
    }
    
    public void setIdoperario(Integer idoperario) {
        this.idoperario = idoperario;
    }

    public Tiposoperario getTiposoperario() {
        return this.tiposoperario;
    }
    
    public void setTiposoperario(Tiposoperario tiposoperario) {
        this.tiposoperario = tiposoperario;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public String getPass() {
        return this.pass;
    }
    
    public void setPass(String pass) {
        this.pass = pass;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Set<Tareas> getTareases() {
        return this.tareases;
    }
    
    public void setTareases(Set<Tareas> tareases) {
        this.tareases = tareases;
    }
}


