package Modelo;
// Generated 05/02/2014 14:26:02 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Ordenrecepcion generated by hbm2java
 */
public class Ordenrecepcion  implements java.io.Serializable {


     private Integer idordenrecepcion;
     private Cliente cliente;
     private String detalle;
     private Date fecha;
     
    public Ordenrecepcion() {
    }

	
    public Ordenrecepcion(Cliente cliente, String detalle, Date fecha) {
        this.cliente = cliente;
        this.detalle = detalle;
        this.fecha = fecha;
    }
   
    public Integer getIdordenrecepcion() {
        return this.idordenrecepcion;
    }
    
    public void setIdordenrecepcion(Integer idordenrecepcion) {
        this.idordenrecepcion = idordenrecepcion;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public String getDetalle() {
        return this.detalle;
    }
    
    public void setDetalle(String detalle) {
        this.detalle = detalle;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

}


