package Modelo;
// Generated 31/03/2014 16:06:45 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Ordenesreparacion generated by hbm2java
 */
public class Ordenesreparacion  implements java.io.Serializable {


     private Integer idordenreparacion;
     private Terceros terceros;
     private Estadosreparacion estadosreparacion;
     private Date fechainicio;
     private Date fechaestimada;
     private Date fechafinalizacion;
     private double precio;
     private String descripcion;
     private Integer numero;
     private Set<Tareas> tareases = new HashSet<Tareas>(0);
     private Set<Auditoriasordenrep> auditoriasordenreps = new HashSet<Auditoriasordenrep>(0);

    public Ordenesreparacion() {
        estadosreparacion=new Estadosreparacion();
        terceros=new Terceros();
    }

	
    public Ordenesreparacion(Terceros terceros, Estadosreparacion estadosreparacion, double precio,String descripcion,int numero) {
        this.terceros = terceros;
        this.estadosreparacion = estadosreparacion;
        this.precio = precio;
        this.descripcion=descripcion;
        this.numero=numero;
    }
    public Ordenesreparacion(Terceros terceros, Estadosreparacion estadosreparacion, Date fechainicio, Date fechaestimada, Date fechafinalizacion, double precio,String descripcion,int numero, Set<Tareas> tareases, Set<Auditoriasordenrep> auditoriasordenreps) {
       this.terceros = terceros;
       this.estadosreparacion = estadosreparacion;
       this.fechainicio = fechainicio;
       this.fechaestimada = fechaestimada;
       this.fechafinalizacion = fechafinalizacion;
       this.precio = precio;
       this.descripcion=descripcion;
       this.numero=numero;
       this.tareases = tareases;
       this.auditoriasordenreps = auditoriasordenreps;
    }
   
    public Integer getIdordenreparacion() {
        return this.idordenreparacion;
    }
    
    public void setIdordenreparacion(Integer idordenreparacion) {
        this.idordenreparacion = idordenreparacion;
    }
    public Terceros getTerceros() {
        return this.terceros;
    }
    
    public void setTerceros(Terceros terceros) {
        this.terceros = terceros;
    }
    public Estadosreparacion getEstadosreparacion() {
        return this.estadosreparacion;
    }
    
    public void setEstadosreparacion(Estadosreparacion estadosreparacion) {
        this.estadosreparacion = estadosreparacion;
    }
    public Date getFechainicio() {
        return this.fechainicio;
    }
    
    public void setFechainicio(Date fechainicio) {
        this.fechainicio = fechainicio;
    }
    public Date getFechaestimada() {
        return this.fechaestimada;
    }
    
    public void setFechaestimada(Date fechaestimada) {
        this.fechaestimada = fechaestimada;
    }
    public Date getFechafinalizacion() {
        return this.fechafinalizacion;
    }
    
    public void setFechafinalizacion(Date fechafinalizacion) {
        this.fechafinalizacion = fechafinalizacion;
    }
    public double getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(double precio) {
        this.precio = precio;
    }
    public Set<Tareas> getTareases() {
        return this.tareases;
    }
    
    public void setTareases(Set<Tareas> tareases) {
        this.tareases = tareases;
    }
    public Set<Auditoriasordenrep> getAuditoriasordenreps() {
        return this.auditoriasordenreps;
    }
    
    public void setAuditoriasordenreps(Set<Auditoriasordenrep> auditoriasordenreps) {
        this.auditoriasordenreps = auditoriasordenreps;
    }

    public String getDescripcion() {
        return descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public Integer getNumero() {
        return numero;
    }

    public void setNumero(Integer numero) {
        this.numero = numero;
    }

}


