package Modelo;
// Generated 05/02/2014 14:26:02 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Persona generated by hbm2java
 */
public abstract class Persona  implements java.io.Serializable {


     private Integer idpersona;
     private int dni;
     private String nombre;
     private String apellido;
     private Date fechaNac;
     private String telFijo;
     private String telMovil;
     private String email;
     private String calle;
     private String numeracion;
     private String depto;

    public Persona() {
    }

	
    public Persona(int dni, String nombre, String apellido, String email) {
        this.dni = dni;
        this.nombre = nombre;
        this.apellido = apellido;
        this.email = email;
    }
    public Persona(int dni, String nombre, String apellido, Date fechaNac, String telFijo, String telMovil, String email, String calle, String numeracion, String depto) {
       this.dni = dni;
       this.nombre = nombre;
       this.apellido = apellido;
       this.fechaNac = fechaNac;
       this.telFijo = telFijo;
       this.telMovil = telMovil;
       this.email = email;
       this.calle = calle;
       this.numeracion = numeracion;
       this.depto = depto;
    }
   
    public Integer getIdpersona() {
        return this.idpersona;
    }
    
    public void setIdpersona(Integer idpersona) {
        this.idpersona = idpersona;
    }
    public int getDni() {
        return this.dni;
    }
    
    public void setDni(int dni) {
        this.dni = dni;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public Date getFechaNac() {
        return this.fechaNac;
    }
    
    public void setFechaNac(Date fechaNac) {
        this.fechaNac = fechaNac;
    }
    public String getTelFijo() {
        return this.telFijo;
    }
    
    public void setTelFijo(String telFijo) {
        this.telFijo = telFijo;
    }
    public String getTelMovil() {
        return this.telMovil;
    }
    
    public void setTelMovil(String telMovil) {
        this.telMovil = telMovil;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getCalle() {
        return this.calle;
    }
    
    public void setCalle(String calle) {
        this.calle = calle;
    }
    public String getNumeracion() {
        return this.numeracion;
    }
    
    public void setNumeracion(String numeracion) {
        this.numeracion = numeracion;
    }
    public String getDepto() {
        return this.depto;
    }
    
    public void setDepto(String depto) {
        this.depto = depto;
    }

}


