package Modelo;
// Generated 31/03/2014 16:06:45 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Presupuestos generated by hbm2java
 */
public class Presupuestos  implements java.io.Serializable {


     private Integer idpresupuesto;
     private Ordenesrecepcion ordenesrecepcion;
     private double precioestimado;
     private boolean esaceptado;
     private String tareas;
     private String opcional;
     private Set<Auditoriaspresupuestos> auditoriaspresupuestoses = new HashSet<Auditoriaspresupuestos>(0);

    public Presupuestos() {
    }

	
    public Presupuestos(Ordenesrecepcion ordenesrecepcion, double precioestimado, boolean esaceptado,String tareas,String opcional) {
        this.ordenesrecepcion = ordenesrecepcion;
        this.precioestimado = precioestimado;
        this.esaceptado = esaceptado;
        this.tareas=tareas;
        this.opcional=opcional;
    }
    public Presupuestos(Ordenesrecepcion ordenesrecepcion, double precioestimado, boolean esaceptado,String tareas,String opcional, Set<Auditoriaspresupuestos> auditoriaspresupuestoses) {
       this.ordenesrecepcion = ordenesrecepcion;
       this.precioestimado = precioestimado;
       this.esaceptado = esaceptado;
       this.tareas=tareas;
       this.opcional=opcional;
       this.auditoriaspresupuestoses = auditoriaspresupuestoses;    
    }
   
    public Integer getIdpresupuesto() {
        return this.idpresupuesto;
    }
    
    public void setIdpresupuesto(Integer idpresupuesto) {
        this.idpresupuesto = idpresupuesto;
    }
    public Ordenesrecepcion getOrdenesrecepcion() {
        return this.ordenesrecepcion;
    }
    
    public void setOrdenesrecepcion(Ordenesrecepcion ordenesrecepcion) {
        this.ordenesrecepcion = ordenesrecepcion;
    }
    public double getPrecioestimado() {
        return this.precioestimado;
    }
    
    public void setPrecioestimado(double precioestimado) {
        this.precioestimado = precioestimado;
    }
    public boolean isEsaceptado() {
        return this.esaceptado;
    }
    
    public void setEsaceptado(boolean esaceptado) {
        this.esaceptado = esaceptado;
    }
    public Set<Auditoriaspresupuestos> getAuditoriaspresupuestoses() {
        return this.auditoriaspresupuestoses;
    }
    
    public void setAuditoriaspresupuestoses(Set<Auditoriaspresupuestos> auditoriaspresupuestoses) {
        this.auditoriaspresupuestoses = auditoriaspresupuestoses;
    }

    public String getTareas() {
        return tareas;
    }

    public void setTareas(String tareas) {
        this.tareas = tareas;
    }

    public String getOpcional() {
        return opcional;
    }

    public void setOpcional(String opcional) {
        this.opcional = opcional;
    }

}


