package Modelo;
// Generated 05/02/2014 14:26:02 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Presupuesto generated by hbm2java
 */
public class Presupuesto  implements java.io.Serializable {


     private Integer idpresupuesto;
     private Ordenrecepcion ordenrecepcion;
     private double precioestimado;
     private boolean esaceptado;
     private Set<Tarea> tareas = new HashSet<Tarea>(0);
     private Set<Auditoriapresupuesto> auditoriapresupuestos = new HashSet<Auditoriapresupuesto>(0);

    public Presupuesto() {
    }

	
    public Presupuesto(Ordenrecepcion ordenrecepcion, double precioestimado, boolean esaceptado) {
        this.ordenrecepcion = ordenrecepcion;
        this.precioestimado = precioestimado;
        this.esaceptado = esaceptado;
    }
    public Presupuesto(Ordenrecepcion ordenrecepcion, double precioestimado, boolean esaceptado, Set<Tarea> tareas, Set<Auditoriapresupuesto> auditoriapresupuestos) {
       this.ordenrecepcion = ordenrecepcion;
       this.precioestimado = precioestimado;
       this.esaceptado = esaceptado;
       this.tareas = tareas;
       this.auditoriapresupuestos = auditoriapresupuestos;
    }
   
    public Integer getIdpresupuesto() {
        return this.idpresupuesto;
    }
    
    public void setIdpresupuesto(Integer idpresupuesto) {
        this.idpresupuesto = idpresupuesto;
    }
    public Ordenrecepcion getOrdenrecepcion() {
        return this.ordenrecepcion;
    }
    
    public void setOrdenrecepcion(Ordenrecepcion ordenrecepcion) {
        this.ordenrecepcion = ordenrecepcion;
    }
    public double getPrecioestimado() {
        return this.precioestimado;
    }
    
    public void setPrecioestimado(double precioestimado) {
        this.precioestimado = precioestimado;
    }
    public boolean isEsaceptado() {
        return this.esaceptado;
    }
    
    public void setEsaceptado(boolean esaceptado) {
        this.esaceptado = esaceptado;
    }
    public Set<Tarea> getTareas() {
        return this.tareas;
    }
    
    public void setTareas(Set<Tarea> tareas) {
        this.tareas = tareas;
    }
    public Set<Auditoriapresupuesto> getAuditoriapresupuestos() {
        return this.auditoriapresupuestos;
    }
    
    public void setAuditoriapresupuestos(Set<Auditoriapresupuesto> auditoriapresupuestos) {
        this.auditoriapresupuestos = auditoriapresupuestos;
    }




}


