package Modelo;
// Generated 31/03/2014 16:06:45 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Presupuestos generated by hbm2java
 */
public class Presupuestos  implements java.io.Serializable {


     private Integer idpresupuesto;
     private Ordenesrecepcion ordenesrecepcion;
     private double precioestimado;
     private boolean esaceptado;
     private Set<Auditoriaspresupuestos> auditoriaspresupuestoses = new HashSet<Auditoriaspresupuestos>(0);
     private Set<Tareas> tareases = new HashSet<Tareas>(0);

    public Presupuestos() {
    }

	
    public Presupuestos(Ordenesrecepcion ordenesrecepcion, double precioestimado, boolean esaceptado) {
        this.ordenesrecepcion = ordenesrecepcion;
        this.precioestimado = precioestimado;
        this.esaceptado = esaceptado;
    }
    public Presupuestos(Ordenesrecepcion ordenesrecepcion, double precioestimado, boolean esaceptado, Set<Auditoriaspresupuestos> auditoriaspresupuestoses, Set<Tareas> tareases) {
       this.ordenesrecepcion = ordenesrecepcion;
       this.precioestimado = precioestimado;
       this.esaceptado = esaceptado;
       this.auditoriaspresupuestoses = auditoriaspresupuestoses;
       this.tareases = tareases;
    }
   
    public Integer getIdpresupuesto() {
        return this.idpresupuesto;
    }
    
    public void setIdpresupuesto(Integer idpresupuesto) {
        this.idpresupuesto = idpresupuesto;
    }
    public Ordenesrecepcion getOrdenesrecepcion() {
        return this.ordenesrecepcion;
    }
    
    public void setOrdenesrecepcion(Ordenesrecepcion ordenesrecepcion) {
        this.ordenesrecepcion = ordenesrecepcion;
    }
    public double getPrecioestimado() {
        return this.precioestimado;
    }
    
    public void setPrecioestimado(double precioestimado) {
        this.precioestimado = precioestimado;
    }
    public boolean isEsaceptado() {
        return this.esaceptado;
    }
    
    public void setEsaceptado(boolean esaceptado) {
        this.esaceptado = esaceptado;
    }
    public Set<Auditoriaspresupuestos> getAuditoriaspresupuestoses() {
        return this.auditoriaspresupuestoses;
    }
    
    public void setAuditoriaspresupuestoses(Set<Auditoriaspresupuestos> auditoriaspresupuestoses) {
        this.auditoriaspresupuestoses = auditoriaspresupuestoses;
    }
    public Set<Tareas> getTareases() {
        return this.tareases;
    }
    
    public void setTareases(Set<Tareas> tareases) {
        this.tareases = tareases;
    }




}


