package Modelo;
// Generated 05/02/2014 14:26:02 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Proveedor generated by hbm2java
 */
public class Proveedor  implements java.io.Serializable {


     private Integer idproveedor;
     private String razonsocial;
     private int cuit;
     private String telefono;
     private String email;
     private String calle;
     private String numeracion;
     private String depto;
     private Set<Provrepuesto> provrepuestos = new HashSet<Provrepuesto>(0);

    public Proveedor() {
    }

	
    public Proveedor(String razonsocial, int cuit, String telefono, String calle, String numeracion) {
        this.razonsocial = razonsocial;
        this.cuit = cuit;
        this.telefono = telefono;
        this.calle = calle;
        this.numeracion = numeracion;
    }
    public Proveedor(String razonsocial, int cuit, String telefono, String email, String calle, String numeracion, String depto, Set<Provrepuesto> provrepuestos) {
       this.razonsocial = razonsocial;
       this.cuit = cuit;
       this.telefono = telefono;
       this.email = email;
       this.calle = calle;
       this.numeracion = numeracion;
       this.depto = depto;
       this.provrepuestos = provrepuestos;
    }
   
    public Integer getIdproveedor() {
        return this.idproveedor;
    }
    
    public void setIdproveedor(Integer idproveedor) {
        this.idproveedor = idproveedor;
    }
    public String getRazonsocial() {
        return this.razonsocial;
    }
    
    public void setRazonsocial(String razonsocial) {
        this.razonsocial = razonsocial;
    }
    public int getCuit() {
        return this.cuit;
    }
    
    public void setCuit(int cuit) {
        this.cuit = cuit;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getCalle() {
        return this.calle;
    }
    
    public void setCalle(String calle) {
        this.calle = calle;
    }
    public String getNumeracion() {
        return this.numeracion;
    }
    
    public void setNumeracion(String numeracion) {
        this.numeracion = numeracion;
    }
    public String getDepto() {
        return this.depto;
    }
    
    public void setDepto(String depto) {
        this.depto = depto;
    }
    public Set<Provrepuesto> getProvrepuestos() {
        return this.provrepuestos;
    }
    
    public void setProvrepuestos(Set<Provrepuesto> provrepuestos) {
        this.provrepuestos = provrepuestos;
    }




}


