package Modelo;
// Generated 05/02/2014 14:26:02 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Repuesto generated by hbm2java
 */
public class Repuesto  implements java.io.Serializable {


     private Integer idrepuesto;
     private String nombre;
     private int stock;
     private Set<Provrepuesto> provrepuestos = new HashSet<Provrepuesto>(0);

    public Repuesto() {
    }

	
    public Repuesto(String nombre, int stock) {
        this.nombre = nombre;
        this.stock = stock;
    }
    public Repuesto(String nombre, int stock, Set<Provrepuesto> provrepuestos) {
       this.nombre = nombre;
       this.stock = stock;
       this.provrepuestos = provrepuestos;
    }
   
    public Integer getIdrepuesto() {
        return this.idrepuesto;
    }
    
    public void setIdrepuesto(Integer idrepuesto) {
        this.idrepuesto = idrepuesto;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public int getStock() {
        return this.stock;
    }
    
    public void setStock(int stock) {
        this.stock = stock;
    }
    public Set<Provrepuesto> getProvrepuestos() {
        return this.provrepuestos;
    }
    
    public void setProvrepuestos(Set<Provrepuesto> provrepuestos) {
        this.provrepuestos = provrepuestos;
    }




}


