package Modelo;
// Generated 05/02/2014 14:26:02 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Tarea generated by hbm2java
 */
public class Tarea  implements java.io.Serializable {


     private Integer idtarea;
     private Ordenreparacion ordenreparacion;
     private Presupuesto presupuesto;
     private Operario operario;
     private String detalle;
     private double precio;
     private boolean esobligatoria;
     private Set<Listarepuestos> listarepuestoses = new HashSet<Listarepuestos>(0);

    public Tarea() {
    }

	
    public Tarea(Presupuesto presupuesto, String detalle, double precio, boolean esobligatoria) {
        this.presupuesto = presupuesto;
        this.detalle = detalle;
        this.precio = precio;
        this.esobligatoria = esobligatoria;
    }
    public Tarea(Ordenreparacion ordenreparacion, Presupuesto presupuesto, Operario operario, String detalle, double precio, boolean esobligatoria, Set<Listarepuestos> listarepuestoses) {
       this.ordenreparacion = ordenreparacion;
       this.presupuesto = presupuesto;
       this.operario = operario;
       this.detalle = detalle;
       this.precio = precio;
       this.esobligatoria = esobligatoria;
       this.listarepuestoses = listarepuestoses;
    }
   
    public Integer getIdtarea() {
        return this.idtarea;
    }
    
    public void setIdtarea(Integer idtarea) {
        this.idtarea = idtarea;
    }
    public Ordenreparacion getOrdenreparacion() {
        return this.ordenreparacion;
    }
    
    public void setOrdenreparacion(Ordenreparacion ordenreparacion) {
        this.ordenreparacion = ordenreparacion;
    }
    public Presupuesto getPresupuesto() {
        return this.presupuesto;
    }
    
    public void setPresupuesto(Presupuesto presupuesto) {
        this.presupuesto = presupuesto;
    }
    public Operario getOperario() {
        return this.operario;
    }
    
    public void setOperario(Operario operario) {
        this.operario = operario;
    }
    public String getDetalle() {
        return this.detalle;
    }
    
    public void setDetalle(String detalle) {
        this.detalle = detalle;
    }
    public double getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(double precio) {
        this.precio = precio;
    }
    public boolean isEsobligatoria() {
        return this.esobligatoria;
    }
    
    public void setEsobligatoria(boolean esobligatoria) {
        this.esobligatoria = esobligatoria;
    }
    public Set<Listarepuestos> getListarepuestoses() {
        return this.listarepuestoses;
    }
    
    public void setListarepuestoses(Set<Listarepuestos> listarepuestoses) {
        this.listarepuestoses = listarepuestoses;
    }




}


