package Modelo;
// Generated 31/03/2014 16:06:45 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Terceros generated by hbm2java
 */
public class Terceros  implements java.io.Serializable {


     private Integer idtercero;
     private String nombre;
     private String apellido;
     private String razonsocial;
     private String cuit;
     private Integer dni;
     private String email;
     private String telefono;
     private String telefonomovil;
     private String calle;
     private Integer altura;
     private String dpto;
     private Boolean esproveedor;
     private Boolean escliente;
     private Set<Ordenesrecepcion> ordenesrecepcions = new HashSet<Ordenesrecepcion>(0);
     private Set<Repuestos> repuestoses = new HashSet<Repuestos>(0);
     private Set<Ordenesreparacion> ordenesreparacions = new HashSet<Ordenesreparacion>(0);

    public Terceros() {
    }

    public Terceros(String nombre, String apellido, String razonsocial, String cuit, Integer dni, String email, String telefono, String telefonomovil, String calle, Integer altura, String dpto, Boolean esproveedor, Boolean escliente, Set<Ordenesrecepcion> ordenesrecepcions, Set<Repuestos> repuestoses, Set<Ordenesreparacion> ordenesreparacions) {
       this.nombre = nombre;
       this.apellido = apellido;
       this.razonsocial = razonsocial;
       this.cuit = cuit;
       this.dni = dni;
       this.email = email;
       this.telefono = telefono;
       this.telefonomovil = telefonomovil;
       this.calle = calle;
       this.altura = altura;
       this.dpto = dpto;
       this.esproveedor = esproveedor;
       this.escliente = escliente;
       this.ordenesrecepcions = ordenesrecepcions;
       this.repuestoses = repuestoses;
       this.ordenesreparacions = ordenesreparacions;
    }
   
    public Integer getIdtercero() {
        return this.idtercero;
    }
    
    public void setIdtercero(Integer idtercero) {
        this.idtercero = idtercero;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getRazonsocial() {
        return this.razonsocial;
    }
    
    public void setRazonsocial(String razonsocial) {
        this.razonsocial = razonsocial;
    }
    public String getCuit() {
        return this.cuit;
    }
    
    public void setCuit(String cuit) {
        this.cuit = cuit;
    }
    public Integer getDni() {
        return this.dni;
    }
    
    public void setDni(Integer dni) {
        this.dni = dni;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getTelefonomovil() {
        return this.telefonomovil;
    }
    
    public void setTelefonomovil(String telefonomovil) {
        this.telefonomovil = telefonomovil;
    }
    public String getCalle() {
        return this.calle;
    }
    
    public void setCalle(String calle) {
        this.calle = calle;
    }
    public Integer getAltura() {
        return this.altura;
    }
    
    public void setAltura(Integer altura) {
        this.altura = altura;
    }
    public String getDpto() {
        return this.dpto;
    }
    
    public void setDpto(String dpto) {
        this.dpto = dpto;
    }
    public Boolean getEsproveedor() {
        return this.esproveedor;
    }
    
    public void setEsproveedor(Boolean esproveedor) {
        this.esproveedor = esproveedor;
    }
    public Boolean getEscliente() {
        return this.escliente;
    }
    
    public void setEscliente(Boolean escliente) {
        this.escliente = escliente;
    }
    public Set<Ordenesrecepcion> getOrdenesrecepcions() {
        return this.ordenesrecepcions;
    }
    
    public void setOrdenesrecepcions(Set<Ordenesrecepcion> ordenesrecepcions) {
        this.ordenesrecepcions = ordenesrecepcions;
    }
    public Set<Repuestos> getRepuestoses() {
        return this.repuestoses;
    }
    
    public void setRepuestoses(Set<Repuestos> repuestoses) {
        this.repuestoses = repuestoses;
    }
    public Set<Ordenesreparacion> getOrdenesreparacions() {
        return this.ordenesreparacions;
    }
    
    public void setOrdenesreparacions(Set<Ordenesreparacion> ordenesreparacions) {
        this.ordenesreparacions = ordenesreparacions;
    }




}


