package Modelo;
// Generated 31/03/2014 16:06:45 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Tiposcalidad generated by hbm2java
 */
public class Tiposcalidad  implements java.io.Serializable {


     private Integer idtipocalidad;
     private String tipo;
     private Set<Repuestos> repuestoses = new HashSet<Repuestos>(0);

    public Tiposcalidad() {
    }

	
    public Tiposcalidad(String tipo) {
        this.tipo = tipo;
    }
    public Tiposcalidad(String tipo, Set<Repuestos> repuestoses) {
       this.tipo = tipo;
       this.repuestoses = repuestoses;
    }
   
    public Integer getIdtipocalidad() {
        return this.idtipocalidad;
    }
    
    public void setIdtipocalidad(Integer idtipocalidad) {
        this.idtipocalidad = idtipocalidad;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public Set<Repuestos> getRepuestoses() {
        return this.repuestoses;
    }
    
    public void setRepuestoses(Set<Repuestos> repuestoses) {
        this.repuestoses = repuestoses;
    }




}


