package Modelo;
// Generated 05/02/2014 14:26:02 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Tipocalidad generated by hbm2java
 */
public class Tipocalidad  implements java.io.Serializable {


     private Integer idtipocalidad;
     private String tipo;
     private Set<Provrepuesto> provrepuestos = new HashSet<Provrepuesto>(0);

    public Tipocalidad() {
    }

	
    public Tipocalidad(String tipo) {
        this.tipo = tipo;
    }
    public Tipocalidad(String tipo, Set<Provrepuesto> provrepuestos) {
       this.tipo = tipo;
       this.provrepuestos = provrepuestos;
    }
   
    public Integer getIdtipocalidad() {
        return this.idtipocalidad;
    }
    
    public void setIdtipocalidad(Integer idtipocalidad) {
        this.idtipocalidad = idtipocalidad;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public Set<Provrepuesto> getProvrepuestos() {
        return this.provrepuestos;
    }
    
    public void setProvrepuestos(Set<Provrepuesto> provrepuestos) {
        this.provrepuestos = provrepuestos;
    }




}


