package Modelo;
// Generated 31/03/2014 16:06:45 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Tiposrepuesto generated by hbm2java
 */
public class Tiposrepuesto  implements java.io.Serializable {


     private Integer idtiporepuesto;
     private String tipo;
     private int stock;
     private Set<Repuestos> repuestoses = new HashSet<Repuestos>(0);

    public Tiposrepuesto() {
    }

	
    public Tiposrepuesto(String tipo, int stock) {
        this.tipo = tipo;
        this.stock = stock;
    }
    public Tiposrepuesto(String tipo, int stock, Set<Repuestos> repuestoses) {
       this.tipo = tipo;
       this.stock = stock;
       this.repuestoses = repuestoses;
    }
   
    public Integer getIdtiporepuesto() {
        return this.idtiporepuesto;
    }
    
    public void setIdtiporepuesto(Integer idtiporepuesto) {
        this.idtiporepuesto = idtiporepuesto;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public int getStock() {
        return this.stock;
    }
    
    public void setStock(int stock) {
        this.stock = stock;
    }
    public Set<Repuestos> getRepuestoses() {
        return this.repuestoses;
    }
    
    public void setRepuestoses(Set<Repuestos> repuestoses) {
        this.repuestoses = repuestoses;
    }




}


